services:
  postgres:
    image: postgres:16
    container_name: hw03_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"

  mongo:
    image: mongo:7
    container_name: hw03_mongo
    ports:
      - "27017:27017"
